use crate::tools::io::error::IoToolError;
use crate::tools::io::security::SecurePathResolver;
use crate::tools::io::utils::validate_single_path;
use serde_json::{json, Value};
use std::fs;
use std::path::PathBuf;
use tokitai::tool;

/// 项目模板生成工具 - 支持创建各种编程语言的项目模板
pub struct ProjectTemplates {
    resolver: SecurePathResolver,
}

impl Default for ProjectTemplates {
    fn default() -> Self {
        Self::new()
    }
}

impl ProjectTemplates {
    pub fn new() -> Self {
        Self {
            resolver: SecurePathResolver::new(),
        }
    }

    #[allow(dead_code)]
    pub fn with_resolver(resolver: SecurePathResolver) -> Self {
        Self { resolver }
    }
}

#[tool]
impl ProjectTemplates {
    /// 创建 Rust 项目模板
    ///
    /// # 参数
    /// - `name`: 项目名称
    /// - `dest`: 目标目录（可选，默认为 ./sandbox/项目文件夹）
    ///
    /// # 返回
    /// 返回创建的项目路径
    pub fn create_rust_project(&self, name: String, dest: Option<String>) -> Result<Value, Value> {
        let project_path = self.resolve_destination(&name, dest)?;

        // 创建目录结构
        let src_dir = project_path.join("src");
        let tests_dir = project_path.join("tests");

        fs::create_dir_all(&src_dir).map_err(|e| {
            IoToolError::DirCreationFailed {
                path: src_dir.to_string_lossy().to_string(),
                message: e.to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        fs::create_dir_all(&tests_dir).map_err(|e| {
            IoToolError::DirCreationFailed {
                path: tests_dir.to_string_lossy().to_string(),
                message: e.to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 Cargo.toml
        let cargo_toml = format!(
            r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[dependencies]
"#,
            name
        );
        fs::write(project_path.join("Cargo.toml"), &cargo_toml).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(project_path.to_string_lossy().to_string()),
                operation: "create_rust_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 src/main.rs
        let main_rs = r#"fn main() {
    println!("Hello, world!");
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_hello() {
        assert_eq!(1 + 1, 2);
    }
}
"#;
        fs::write(src_dir.join("main.rs"), main_rs).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(src_dir.to_string_lossy().to_string()),
                operation: "create_rust_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 .gitignore
        let gitignore = r#"# Generated by Cargo
/target/

# Cargo.lock for libraries
# Cargo.lock

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"#;
        fs::write(project_path.join(".gitignore"), gitignore).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(project_path.to_string_lossy().to_string()),
                operation: "create_rust_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        Ok(IoToolError::success_response(
            "create_rust_project",
            json!({
                "project_path": project_path.to_string_lossy().to_string(),
                "language": "rust",
                "structure": {
                    "files": ["Cargo.toml", ".gitignore", "src/main.rs"],
                    "directories": ["src", "tests"]
                },
                "message": format!("✅ Rust 项目已创建：{}", project_path.display())
            }),
        ))
    }

    /// 创建 Python 项目模板
    ///
    /// # 参数
    /// - `name`: 项目名称
    /// - `dest`: 目标目录（可选，默认为 ./sandbox/项目文件夹）
    ///
    /// # 返回
    /// 返回创建的项目路径
    pub fn create_python_project(
        &self,
        name: String,
        dest: Option<String>,
    ) -> Result<Value, Value> {
        let project_path = self.resolve_destination(&name, dest)?;

        // 创建目录结构
        let src_dir = project_path.join("src").join(&name);
        let tests_dir = project_path.join("tests");

        fs::create_dir_all(&src_dir).map_err(|e| {
            IoToolError::DirCreationFailed {
                path: src_dir.to_string_lossy().to_string(),
                message: e.to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        fs::create_dir_all(&tests_dir).map_err(|e| {
            IoToolError::DirCreationFailed {
                path: tests_dir.to_string_lossy().to_string(),
                message: e.to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 pyproject.toml
        let pyproject = format!(
            r#"[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{}"
version = "0.1.0"
description = "A Python project"
authors = [{{name = "Author", email = "author@example.com"}}]

[tool.pytest.ini_options]
testpaths = ["tests"]
"#,
            name
        );
        fs::write(project_path.join("pyproject.toml"), &pyproject).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(project_path.to_string_lossy().to_string()),
                operation: "create_python_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 src/__init__.py
        let init_py = format!(
            r#""""{} package.""""

__version__ = "0.1.0"

def hello():
    """Return a greeting."""
    return "Hello from {}!"
"#,
            name, name
        );
        fs::write(src_dir.join("__init__.py"), &init_py).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(src_dir.to_string_lossy().to_string()),
                operation: "create_python_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 tests/test_main.py
        let test_py = r#"from src import hello

def test_hello():
    """Test the hello function."""
    assert hello() == "Hello from myproject!"
"#;
        fs::write(tests_dir.join("test_main.py"), test_py).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(tests_dir.to_string_lossy().to_string()),
                operation: "create_python_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 README.md
        let readme = format!(
            r#"# {}

{} project description.

## Installation

```bash
pip install -e .
```

## Usage

```python
from {} import hello
print(hello())
```

## Development

```bash
pip install -e ".[dev]"
pytest
```
"#,
            name, name, name
        );
        fs::write(project_path.join("README.md"), &readme).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(project_path.to_string_lossy().to_string()),
                operation: "create_python_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 .gitignore
        let gitignore = r#"# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
env/
ENV/
.venv

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"#;
        fs::write(project_path.join(".gitignore"), gitignore).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(project_path.to_string_lossy().to_string()),
                operation: "create_python_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        Ok(IoToolError::success_response(
            "create_python_project",
            json!({
                "project_path": project_path.to_string_lossy().to_string(),
                "language": "python",
                "structure": {
                    "files": ["pyproject.toml", "README.md", ".gitignore", "src/__init__.py", "tests/test_main.py"],
                    "directories": [format!("src/{}", name), "tests"]
                },
                "message": format!("✅ Python 项目已创建：{}", project_path.display())
            }),
        ))
    }

    /// 创建 Node.js 项目模板
    ///
    /// # 参数
    /// - `name`: 项目名称
    /// - `dest`: 目标目录（可选，默认为 ./sandbox/项目文件夹）
    ///
    /// # 返回
    /// 返回创建的项目路径
    pub fn create_nodejs_project(
        &self,
        name: String,
        dest: Option<String>,
    ) -> Result<Value, Value> {
        let project_path = self.resolve_destination(&name, dest)?;

        // 创建目录结构
        let src_dir = project_path.join("src");
        let test_dir = project_path.join("test");

        fs::create_dir_all(&src_dir).map_err(|e| {
            IoToolError::DirCreationFailed {
                path: src_dir.to_string_lossy().to_string(),
                message: e.to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        fs::create_dir_all(&test_dir).map_err(|e| {
            IoToolError::DirCreationFailed {
                path: test_dir.to_string_lossy().to_string(),
                message: e.to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 package.json
        let package_json = format!(
            r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "{} project",
  "main": "src/index.js",
  "type": "module",
  "scripts": {{
    "start": "node src/index.js",
    "test": "node --test test/"
  }},
  "keywords": [],
  "author": "",
  "license": "MIT"
}}
"#,
            name, name
        );
        fs::write(project_path.join("package.json"), &package_json).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(project_path.to_string_lossy().to_string()),
                operation: "create_nodejs_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 src/index.js
        let index_js = r#"/**
 * Main entry point
 */

export function hello() {
    return "Hello from Node.js!";
}

// Main execution
if (import.meta.url === `file://${process.argv[1]}`) {
    console.log(hello());
}
"#;
        fs::write(src_dir.join("index.js"), index_js).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(src_dir.to_string_lossy().to_string()),
                operation: "create_nodejs_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 test/index.test.js
        let test_js = r#"import { hello } from '../src/index.js';
import assert from 'node:assert';
import test from 'node:test';

test('hello function', () => {
    assert.strictEqual(hello(), 'Hello from Node.js!');
});
"#;
        fs::write(test_dir.join("index.test.js"), test_js).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(test_dir.to_string_lossy().to_string()),
                operation: "create_nodejs_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 README.md
        let readme = format!(
            r#"# {}

{} project description.

## Installation

```bash
npm install
```

## Usage

```bash
npm start
```

## Testing

```bash
npm test
```
"#,
            name, name
        );
        fs::write(project_path.join("README.md"), &readme).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(project_path.to_string_lossy().to_string()),
                operation: "create_nodejs_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        // 创建 .gitignore
        let gitignore = r#"# Node modules
node_modules/

# Build output
dist/
build/

# Logs
*.log
npm-debug.log*

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
"#;
        fs::write(project_path.join(".gitignore"), gitignore).map_err(|e| {
            IoToolError::IoError {
                message: e.to_string(),
                path: Some(project_path.to_string_lossy().to_string()),
                operation: "create_nodejs_project".to_string(),
                suggestion: "请检查目标目录的权限设置".to_string(),
            }
            .to_value()
        })?;

        Ok(IoToolError::success_response(
            "create_nodejs_project",
            json!({
                "project_path": project_path.to_string_lossy().to_string(),
                "language": "nodejs",
                "structure": {
                    "files": ["package.json", "README.md", ".gitignore", "src/index.js", "test/index.test.js"],
                    "directories": ["src", "test"]
                },
                "message": format!("✅ Node.js 项目已创建：{}", project_path.display())
            }),
        ))
    }

    /// 创建通用项目目录结构
    ///
    /// # 参数
    /// - `name`: 项目名称
    /// - `structure`: 目录结构描述（JSON 格式，可选）
    /// - `dest`: 目标目录（可选，默认为 ./sandbox/项目文件夹）
    ///
    /// # 返回
    /// 返回创建的项目路径
    pub fn create_custom_project(
        &self,
        name: String,
        structure: Option<String>,
        dest: Option<String>,
    ) -> Result<Value, Value> {
        let project_path = self.resolve_destination(&name, dest)?;

        // 默认结构
        let default_structure =
            r#"{"dirs": ["src", "tests", "docs"], "files": ["README.md", ".gitignore"]}"#;
        let structure_str = structure.as_deref().unwrap_or(default_structure);

        // 解析 JSON 结构
        let structure_json: serde_json::Value =
            serde_json::from_str(structure_str).map_err(|e| {
                IoToolError::InvalidJson {
                    input: structure_str.to_string(),
                    message: e.to_string(),
                    suggestion: "请提供有效的 JSON 格式，包含 dirs 和 files 数组".to_string(),
                }
                .to_value()
            })?;

        let mut created_files = Vec::new();
        let mut created_dirs = Vec::new();

        // 创建目录
        if let Some(dirs) = structure_json.get("dirs").and_then(|v| v.as_array()) {
            for dir in dirs {
                if let Some(dir_name) = dir.as_str() {
                    let dir_path = project_path.join(dir_name);
                    fs::create_dir_all(&dir_path).map_err(|e| {
                        IoToolError::DirCreationFailed {
                            path: dir_name.to_string(),
                            message: e.to_string(),
                            suggestion: "请检查目标目录的权限设置".to_string(),
                        }
                        .to_value()
                    })?;
                    created_dirs.push(dir_name.to_string());
                }
            }
        }

        // 创建文件
        if let Some(files) = structure_json.get("files").and_then(|v| v.as_array()) {
            for file in files {
                if let Some(file_name) = file.as_str() {
                    let file_path = project_path.join(file_name);
                    let content = match file_name {
                        "README.md" => format!("# {}\n\nProject description.\n", name),
                        ".gitignore" => String::from("target/\n__pycache__/\nnode_modules/\n"),
                        _ => String::new(),
                    };
                    fs::write(&file_path, &content).map_err(|e| {
                        IoToolError::IoError {
                            message: e.to_string(),
                            path: Some(file_path.to_string_lossy().to_string()),
                            operation: "create_custom_project".to_string(),
                            suggestion: "请检查目标目录的权限设置".to_string(),
                        }
                        .to_value()
                    })?;
                    created_files.push(file_name.to_string());
                }
            }
        }

        Ok(IoToolError::success_response(
            "create_custom_project",
            json!({
                "project_path": project_path.to_string_lossy().to_string(),
                "language": "custom",
                "structure": {
                    "directories": created_dirs,
                    "files": created_files
                },
                "message": format!("✅ 自定义项目已创建：{}", project_path.display())
            }),
        ))
    }
}

impl ProjectTemplates {
    /// 解析目标路径
    fn resolve_destination(&self, name: &str, dest: Option<String>) -> Result<PathBuf, Value> {
        match dest {
            Some(d) => {
                // 验证提供的路径
                let base_path_str = validate_single_path(&self.resolver, &d)?;
                let base_path = PathBuf::from(base_path_str);

                // 只检查最终路径是否存在，不检查父目录
                // 如果路径存在且是目录，返回错误
                if base_path.exists() {
                    return Err(IoToolError::AlreadyExists {
                        path: base_path.to_string_lossy().to_string(),
                        suggestion: "请使用不同的项目名称或删除现有目录".to_string(),
                    }
                    .to_value());
                }

                Ok(base_path)
            }
            None => {
                // 默认创建到 sandbox 目录
                let sandbox_dir = std::env::current_dir()
                    .map_err(|e| {
                        IoToolError::IoError {
                            message: e.to_string(),
                            path: None,
                            operation: "get_current_dir".to_string(),
                            suggestion: "请检查当前工作目录是否有效".to_string(),
                        }
                        .to_value()
                    })?
                    .join("sandbox");

                // 确保 sandbox 目录存在
                fs::create_dir_all(&sandbox_dir).map_err(|e| {
                    IoToolError::DirCreationFailed {
                        path: sandbox_dir.to_string_lossy().to_string(),
                        message: e.to_string(),
                        suggestion: "请检查项目根目录的权限设置".to_string(),
                    }
                    .to_value()
                })?;

                Ok(sandbox_dir.join(name))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// 获取测试临时目录路径（在当前目录下，避免沙箱问题）
    fn get_test_temp_dir(name: &str) -> PathBuf {
        let current_dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        // 使用时间戳和随机数确保唯一性
        let unique_id = format!(
            "{}_{}_{}",
            name,
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        );
        // 不预先创建目录，让测试自己管理
        current_dir.join("target").join("test_tmp").join(unique_id)
    }

    #[test]
    fn test_create_rust_project() {
        let templates = ProjectTemplates::with_resolver(SecurePathResolver::new_for_tests());
        // 直接使用 sandbox 目录下的唯一路径
        let sandbox = std::env::current_dir().unwrap().join("sandbox");
        let _ = std::fs::create_dir_all(&sandbox);
        let project_path = sandbox.join(format!(
            "test_rust_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));

        // 确保项目路径不存在
        let _ = std::fs::remove_dir_all(&project_path);

        let result = templates.create_rust_project(
            "test_rust".to_string(),
            Some(project_path.to_string_lossy().to_string()),
        );

        // 如果失败，打印错误信息
        if result.is_err() {
            eprintln!("Error path: {:?}", project_path);
            eprintln!("Error: {:?}", result.as_ref().unwrap_err());
        }

        assert!(result.is_ok());
        let value = result.unwrap();
        assert_eq!(value["status"], "success");
        assert!(project_path.join("Cargo.toml").exists());
        assert!(project_path.join("src").join("main.rs").exists());
        assert!(project_path.join("tests").exists());

        let _ = std::fs::remove_dir_all(&project_path);
    }

    #[test]
    fn test_create_python_project() {
        let templates = ProjectTemplates::with_resolver(SecurePathResolver::new_for_tests());
        let sandbox = std::env::current_dir().unwrap().join("sandbox");
        let _ = std::fs::create_dir_all(&sandbox);
        let project_path = sandbox.join(format!(
            "test_python_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));

        let _ = std::fs::remove_dir_all(&project_path);

        let result = templates.create_python_project(
            "test_python".to_string(),
            Some(project_path.to_string_lossy().to_string()),
        );

        assert!(result.is_ok());
        assert_eq!(result.unwrap()["status"], "success");
        assert!(project_path.join("pyproject.toml").exists());
        assert!(project_path.join("src").join("test_python").exists());

        let _ = std::fs::remove_dir_all(&project_path);
    }

    #[test]
    fn test_create_nodejs_project() {
        let templates = ProjectTemplates::with_resolver(SecurePathResolver::new_for_tests());
        let sandbox = std::env::current_dir().unwrap().join("sandbox");
        let _ = std::fs::create_dir_all(&sandbox);
        let project_path = sandbox.join(format!(
            "test_nodejs_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));

        let _ = std::fs::remove_dir_all(&project_path);

        let result = templates.create_nodejs_project(
            "test_nodejs".to_string(),
            Some(project_path.to_string_lossy().to_string()),
        );

        assert!(result.is_ok());
        assert_eq!(result.unwrap()["status"], "success");
        assert!(project_path.join("package.json").exists());
        assert!(project_path.join("src").join("index.js").exists());

        let _ = std::fs::remove_dir_all(&project_path);
    }

    #[test]
    fn test_create_custom_project() {
        let templates = ProjectTemplates::with_resolver(SecurePathResolver::new_for_tests());
        let sandbox = std::env::current_dir().unwrap().join("sandbox");
        let _ = std::fs::create_dir_all(&sandbox);
        let project_path = sandbox.join(format!(
            "test_custom_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));

        let _ = std::fs::remove_dir_all(&project_path);

        let structure = r#"{"dirs": ["src", "tests"], "files": ["README.md"]}"#;

        let result = templates.create_custom_project(
            "test_custom".to_string(),
            Some(structure.to_string()),
            Some(project_path.to_string_lossy().to_string()),
        );

        assert!(result.is_ok());
        assert_eq!(result.unwrap()["status"], "success");
        assert!(project_path.join("src").exists());
        assert!(project_path.join("tests").exists());
        assert!(project_path.join("README.md").exists());

        let _ = std::fs::remove_dir_all(&project_path);
    }

    #[test]
    fn test_create_project_already_exists() {
        let templates = ProjectTemplates::with_resolver(SecurePathResolver::new_for_tests());
        let sandbox = std::env::current_dir().unwrap().join("sandbox");
        let _ = std::fs::create_dir_all(&sandbox);
        let project_path = sandbox.join(format!(
            "test_exists_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));

        // 先创建项目
        let result1 = templates.create_rust_project(
            "test_exists".to_string(),
            Some(project_path.to_string_lossy().to_string()),
        );
        assert!(result1.is_ok());

        // 再次创建应该失败
        let result2 = templates.create_rust_project(
            "test_exists".to_string(),
            Some(project_path.to_string_lossy().to_string()),
        );

        assert!(result2.is_err());
        let err = result2.unwrap_err();
        assert!(err.get("error").is_some());

        let _ = std::fs::remove_dir_all(&project_path);
    }
}
