use std::fs;
use std::path::PathBuf;
use tokitai::tool;

/// 项目模板生成工具 - 支持创建各种编程语言的项目模板
pub struct ProjectTemplates;

/// 项目配置选项
#[derive(Debug, Clone)]
pub struct ProjectConfig {
    pub name: String,
    pub template: String,
    pub dest: PathBuf,
}

#[tool]
impl ProjectTemplates {
    /// 创建 Rust 项目模板
    ///
    /// # 参数
    /// - `name`: 项目名称
    /// - `dest`: 目标目录（可选，默认为 ./sandbox/项目文件夹）
    ///
    /// # 返回
    /// 返回创建的项目路径
    pub fn create_rust_project(&self, name: String, dest: Option<String>) -> Result<String, String> {
        let project_path = match dest {
            Some(d) => PathBuf::from(d),
            None => {
                // 默认创建到 sandbox 目录
                let sandbox_dir = std::env::current_dir()
                    .map_err(|e| format!("获取当前目录失败：{}", e))?
                    .join("sandbox");
                // 确保 sandbox 目录存在
                fs::create_dir_all(&sandbox_dir)
                    .map_err(|e| format!("创建 sandbox 目录失败：{}", e))?;
                sandbox_dir.join(&name)
            }
        };

        // 创建目录结构
        let src_dir = project_path.join("src");
        let tests_dir = project_path.join("tests");

        fs::create_dir_all(&src_dir)
            .map_err(|e| format!("创建 src 目录失败：{}", e))?;
        fs::create_dir_all(&tests_dir)
            .map_err(|e| format!("创建 tests 目录失败：{}", e))?;

        // 创建 Cargo.toml
        let cargo_toml = format!(
            r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[dependencies]
"#, name
        );
        fs::write(project_path.join("Cargo.toml"), cargo_toml)
            .map_err(|e| format!("创建 Cargo.toml 失败：{}", e))?;

        // 创建 src/main.rs
        let main_rs = r#"fn main() {
    println!("Hello, world!");
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_hello() {
        assert_eq!(1 + 1, 2);
    }
}
"#;
        fs::write(src_dir.join("main.rs"), main_rs)
            .map_err(|e| format!("创建 main.rs 失败：{}", e))?;

        // 创建 .gitignore
        let gitignore = r#"# Generated by Cargo
/target/

# Cargo.lock for libraries
# Cargo.lock

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"#;
        fs::write(project_path.join(".gitignore"), gitignore)
            .map_err(|e| format!("创建 .gitignore 失败：{}", e))?;

        Ok(format!(
            "✅ Rust 项目已创建：{}\n\n目录结构:\n├── Cargo.toml\n├── .gitignore\n├── src/\n│   └── main.rs\n└── tests/",
            project_path.display()
        ))
    }

    /// 创建 Python 项目模板
    ///
    /// # 参数
    /// - `name`: 项目名称
    /// - `dest`: 目标目录（可选，默认为 ./sandbox/项目文件夹）
    ///
    /// # 返回
    /// 返回创建的项目路径
    pub fn create_python_project(&self, name: String, dest: Option<String>) -> Result<String, String> {
        let project_path = match dest {
            Some(d) => PathBuf::from(d),
            None => {
                // 默认创建到 sandbox 目录
                let sandbox_dir = std::env::current_dir()
                    .map_err(|e| format!("获取当前目录失败：{}", e))?
                    .join("sandbox");
                // 确保 sandbox 目录存在
                fs::create_dir_all(&sandbox_dir)
                    .map_err(|e| format!("创建 sandbox 目录失败：{}", e))?;
                sandbox_dir.join(&name)
            }
        };

        // 创建目录结构
        let src_dir = project_path.join("src").join(&name);
        let tests_dir = project_path.join("tests");

        fs::create_dir_all(&src_dir)
            .map_err(|e| format!("创建 src 目录失败：{}", e))?;
        fs::create_dir_all(&tests_dir)
            .map_err(|e| format!("创建 tests 目录失败：{}", e))?;

        // 创建 pyproject.toml
        let pyproject = format!(
            r#"[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{}"
version = "0.1.0"
description = "A Python project"
authors = [{{name = "Author", email = "author@example.com"}}]

[tool.pytest.ini_options]
testpaths = ["tests"]
"#, name
        );
        fs::write(project_path.join("pyproject.toml"), pyproject)
            .map_err(|e| format!("创建 pyproject.toml 失败：{}", e))?;

        // 创建 src/__init__.py
        let init_py = format!(
            r#""""{} package.""""

__version__ = "0.1.0"

def hello():
    """Return a greeting."""
    return "Hello from {}!"
"#, name, name
        );
        fs::write(src_dir.join("__init__.py"), init_py)
            .map_err(|e| format!("创建 __init__.py 失败：{}", e))?;

        // 创建 tests/test_main.py
        let test_py = r#"from src import hello

def test_hello():
    """Test the hello function."""
    assert hello() == "Hello from myproject!"
"#;
        fs::write(tests_dir.join("test_main.py"), test_py)
            .map_err(|e| format!("创建 test_main.py 失败：{}", e))?;

        // 创建 README.md
        let readme = format!(
            r#"# {}

{} project description.

## Installation

```bash
pip install -e .
```

## Usage

```python
from {} import hello
print(hello())
```

## Development

```bash
pip install -e ".[dev]"
pytest
```
"#, name, name, name
        );
        fs::write(project_path.join("README.md"), readme)
            .map_err(|e| format!("创建 README.md 失败：{}", e))?;

        // 创建 .gitignore
        let gitignore = r#"# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
env/
ENV/
.venv

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"#;
        fs::write(project_path.join(".gitignore"), gitignore)
            .map_err(|e| format!("创建 .gitignore 失败：{}", e))?;

        Ok(format!(
            "✅ Python 项目已创建：{}\n\n目录结构:\n├── pyproject.toml\n├── README.md\n├── .gitignore\n├── src/\n│   └── {}/\n│       └── __init__.py\n└── tests/\n    └── test_main.py",
            project_path.display(), name
        ))
    }

    /// 创建 Node.js 项目模板
    ///
    /// # 参数
    /// - `name`: 项目名称
    /// - `dest`: 目标目录（可选，默认为 ./sandbox/项目文件夹）
    ///
    /// # 返回
    /// 返回创建的项目路径
    pub fn create_nodejs_project(&self, name: String, dest: Option<String>) -> Result<String, String> {
        let project_path = match dest {
            Some(d) => PathBuf::from(d),
            None => {
                // 默认创建到 sandbox 目录
                let sandbox_dir = std::env::current_dir()
                    .map_err(|e| format!("获取当前目录失败：{}", e))?
                    .join("sandbox");
                // 确保 sandbox 目录存在
                fs::create_dir_all(&sandbox_dir)
                    .map_err(|e| format!("创建 sandbox 目录失败：{}", e))?;
                sandbox_dir.join(&name)
            }
        };

        // 创建目录结构
        let src_dir = project_path.join("src");
        let test_dir = project_path.join("test");

        fs::create_dir_all(&src_dir)
            .map_err(|e| format!("创建 src 目录失败：{}", e))?;
        fs::create_dir_all(&test_dir)
            .map_err(|e| format!("创建 test 目录失败：{}", e))?;

        // 创建 package.json
        let package_json = format!(
            r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "{} project",
  "main": "src/index.js",
  "type": "module",
  "scripts": {{
    "start": "node src/index.js",
    "test": "node --test test/"
  }},
  "keywords": [],
  "author": "",
  "license": "MIT"
}}
"#, name, name
        );
        fs::write(project_path.join("package.json"), package_json)
            .map_err(|e| format!("创建 package.json 失败：{}", e))?;

        // 创建 src/index.js
        let index_js = r#"/**
 * Main entry point
 */

export function hello() {
    return "Hello from Node.js!";
}

// Main execution
if (import.meta.url === `file://${process.argv[1]}`) {
    console.log(hello());
}
"#;
        fs::write(src_dir.join("index.js"), index_js)
            .map_err(|e| format!("创建 index.js 失败：{}", e))?;

        // 创建 test/index.test.js
        let test_js = r#"import { hello } from '../src/index.js';
import assert from 'node:assert';
import test from 'node:test';

test('hello function', () => {
    assert.strictEqual(hello(), 'Hello from Node.js!');
});
"#;
        fs::write(test_dir.join("index.test.js"), test_js)
            .map_err(|e| format!("创建 index.test.js 失败：{}", e))?;

        // 创建 README.md
        let readme = format!(
            r#"# {}

{} project description.

## Installation

```bash
npm install
```

## Usage

```bash
npm start
```

## Testing

```bash
npm test
```
"#, name, name
        );
        fs::write(project_path.join("README.md"), readme)
            .map_err(|e| format!("创建 README.md 失败：{}", e))?;

        // 创建 .gitignore
        let gitignore = r#"# Node modules
node_modules/

# Build output
dist/
build/

# Logs
*.log
npm-debug.log*

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
"#;
        fs::write(project_path.join(".gitignore"), gitignore)
            .map_err(|e| format!("创建 .gitignore 失败：{}", e))?;

        Ok(format!(
            "✅ Node.js 项目已创建：{}\n\n目录结构:\n├── package.json\n├── README.md\n├── .gitignore\n├── src/\n│   └── index.js\n└── test/\n    └── index.test.js",
            project_path.display()
        ))
    }

    /// 创建通用项目目录结构
    ///
    /// # 参数
    /// - `name`: 项目名称
    /// - `structure`: 目录结构描述（JSON 格式，可选）
    /// - `dest`: 目标目录（可选，默认为 ./sandbox/项目文件夹）
    ///
    /// # 返回
    /// 返回创建的项目路径
    pub fn create_custom_project(
        &self,
        name: String,
        structure: Option<String>,
        dest: Option<String>,
    ) -> Result<String, String> {
        let project_path = match dest {
            Some(d) => PathBuf::from(d),
            None => {
                // 默认创建到 sandbox 目录
                let sandbox_dir = std::env::current_dir()
                    .map_err(|e| format!("获取当前目录失败：{}", e))?
                    .join("sandbox");
                // 确保 sandbox 目录存在
                fs::create_dir_all(&sandbox_dir)
                    .map_err(|e| format!("创建 sandbox 目录失败：{}", e))?;
                sandbox_dir.join(&name)
            }
        };

        // 默认结构
        let default_structure = r#"{"dirs": ["src", "tests", "docs"], "files": ["README.md", ".gitignore"]}"#;
        let structure_str = structure.as_deref().unwrap_or(default_structure);

        // 解析 JSON 结构
        let structure_json: serde_json::Value = serde_json::from_str(structure_str)
            .map_err(|e| format!("解析结构 JSON 失败：{}", e))?;

        // 创建目录
        if let Some(dirs) = structure_json.get("dirs").and_then(|v| v.as_array()) {
            for dir in dirs {
                if let Some(dir_name) = dir.as_str() {
                    let dir_path = project_path.join(dir_name);
                    fs::create_dir_all(&dir_path)
                        .map_err(|e| format!("创建目录 {} 失败：{}", dir_name, e))?;
                }
            }
        }

        // 创建文件
        if let Some(files) = structure_json.get("files").and_then(|v| v.as_array()) {
            for file in files {
                if let Some(file_name) = file.as_str() {
                    let file_path = project_path.join(file_name);
                    let content = match file_name {
                        "README.md" => format!("# {}\n\nProject description.\n", name),
                        ".gitignore" => String::from("target/\n__pycache__/\nnode_modules/\n"),
                        _ => String::new(),
                    };
                    fs::write(&file_path, content)
                        .map_err(|e| format!("创建文件 {} 失败：{}", file_name, e))?;
                }
            }
        }

        Ok(format!(
            "✅ 自定义项目已创建：{}",
            project_path.display()
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_create_rust_project() {
        let templates = ProjectTemplates;
        let tmpdir = tempdir().unwrap();
        let project_path = tmpdir.path().join("test_rust");

        let result = templates.create_rust_project(
            "test_rust".to_string(),
            Some(project_path.to_string_lossy().to_string()),
        );

        assert!(result.is_ok());
        assert!(project_path.join("Cargo.toml").exists());
        assert!(project_path.join("src").join("main.rs").exists());
        assert!(project_path.join("tests").exists());
    }

    #[test]
    fn test_create_python_project() {
        let templates = ProjectTemplates;
        let tmpdir = tempdir().unwrap();
        let project_path = tmpdir.path().join("test_python");

        let result = templates.create_python_project(
            "test_python".to_string(),
            Some(project_path.to_string_lossy().to_string()),
        );

        assert!(result.is_ok());
        assert!(project_path.join("pyproject.toml").exists());
        assert!(project_path.join("src").join("test_python").exists());
    }
}
