import fs from "node:fs";
import assert from "node:assert/strict";
const read=(path)=>fs.readFileSync(path,"utf8");
const html=read("frontend/index.html"),js=read("frontend/scientific-infrastructure.js"),app=read("frontend/app.js"),css=read("frontend/styles.css"),overrides=read("frontend/professional-overrides.css"),web=read("src/web.rs"),core=read("src/scientific_infrastructure.rs");

for(const route of ["/api/event-center","/api/event-center/mutate","/api/universal-search","/api/workspace-snapshots","/api/workspace-snapshots/create","/api/workspace-snapshots/action"]) assert.ok(web.includes(route),`missing ${route}`);
for(const tool of ["atlas_event_center","atlas_universal_search","atlas_workspace_snapshot"]) assert.ok(web.includes(tool),`missing Agent tool ${tool}`);
assert.match(core,/core\s*\.\s*timeline\(None\)/,"event center must project Atlas Core Event Bus history");
assert.match(core,/WorkspaceTimeMachine/);assert.match(core,/NavigationTarget/);assert.match(core,/object_versions/);
assert.match(html,/id="global-search-input"/);assert.match(html,/id="global-search-scope-menu"/);assert.match(html,/id="scientific-event-center"/);assert.match(html,/id="workspace-time-machine"/);
assert.match(html,/data-activity-panel="events"/);assert.match(html,/data-activity-panel="snapshots"/);
assert.ok(!js.includes('openPanel?.("search")'),"Universal Search must not open a side panel");
assert.ok(!js.includes('window.open(url,"_blank"'),"Search results must use Atlas internal navigation");
assert.match(app,/await openUrlInAppBrowser\(internalUrl\)/,"URL search results must open in Atlas internal browser");
assert.match(app,/AtlasResearchOS\?\.selectObject/,"Scientific Object results must route to Research OS");
assert.match(js,/download_url|web_url|link/,"External search URL variants must be normalized");
assert.match(js,/pdf_url|landing_page|doi\.org/,"Paper and dataset navigation variants must be normalized");
assert.match(js,/payload\.urls\?\.landing_page/,"Normalized papers must use their nested landing-page URL");
assert.match(js,/payload\.urls\?\.local_path/,"Local paper results must open their nested workspace path");
assert.match(js,/payload\.external_ids\?\.doi/,"Paper DOI navigation must use nested external identifiers");
assert.match(app,/restoreContext\.snapshot_id/,"Snapshot search results must be navigable");
assert.match(app,/restoreContext\.terminal_id/,"Terminal-history search results must be navigable");
assert.match(js,/universal-search-error/,"Search provider failures must be visible in Atlas");
assert.match(js,/universal-search-popover/,"Universal Search must render below the topbar input");
assert.match(js,/popover\.append\(results\)/,"Universal Search popover must contain results only");
assert.ok(!/popover\.append\(health,results,preview\)/.test(js),"Search filters and interpretation must stay out of result popover");
assert.ok(!/activeActivityPanel === "ssh"[\s\S]{0,160}\? Math\./.test(app),"SSH must use Navigation flyout width");
assert.ok(!/\["search", "events", "snapshots"\]\.includes\(activeActivityPanel\)/.test(app),"Event infrastructure must use Navigation flyout width");
assert.match(overrides,/\.scientific-event-panel \.event-timeline,[^\n]*\.scientific-event-panel \.event-inspector\{display:none\}/,"Event Center must adapt to compact Navigation flyout");
assert.ok(!/data-activity-panel="search"/.test(html),"legacy sidebar search entry remains");
assert.equal((html.match(/id="research-os-toggle"/g)||[]).length,1,"Research OS must have exactly one top trigger");
assert.ok(!/research-domains-footer[\s\S]{0,300}research-os-toggle/.test(html),"legacy bottom Research OS button remains");
for(const scope of ["papers","datasets","models","github","experiments","hypotheses","evidence","notifications","ssh_hosts","docker","terminal_history","settings","commands"]) assert.ok(js.includes(`\"${scope}\"`),`missing global search scope ${scope}`);
assert.match(js,/atlas:before-agent-execution|before_agent/);assert.match(app,/AtlasWorkspaceBridge/);assert.match(css,/research-os-top-trigger/);assert.match(css,/global-search-shell/);
assert.ok(!/<iframe/i.test(js),"scientific infrastructure script must not embed external applications");
console.log("Scientific infrastructure wiring checks passed");
